### ISSUE TITLE
CreateTaggableTable gets republished each time a migration from a different library is published

### ISSUE THREAD

**Issue by Scaenicus** [cviebrock/eloquent-taggable#106]
# Reproduce
+ Run `php artisan vendor:publish --tag=migrations` thrice
  + `class CreateTaggableTable` gets created 3 times (each with a new timestamp)
  + However even the first time would be unnecessary since I still can find the previous version's `0000_00_00_000000_create_taggable_table` in the migrations.
+ Also tested after `composer dumpautoload` in between, but still the migrations get republished each time.

**Comment by cviebrock** [comment]
Yeah, I made some changes to the migration code.  In short, if you are just upgrading from an old version, and already have the required tables/migrations, you can skip the `artisan vendor:publish` step.  That would only apply to new installs.
