### ISSUE TITLE
Error in migration when using postgres.

### ISSUE THREAD

**Issue by 0528Makoto** [cviebrock/eloquent-taggable#122]
-   Eloquent Taggable Version: v8.0.2
-   Laravel Version: v8.34.0
-   PHP Version: 8.0.1
-   Database Driver & Version: PostgreSQL 13.1

### Description:

Then migration  `Migrating: 2021_03_30_111045_create_taggable_table`  gives an error when using the postgres with Laravel. Running  `php artisan migrate`  on a fresh installation gives the following error.

```
Illuminate\Database\QueryException  : SQLSTATE[42704]: Undefined object: 7 ERROR:  collation "utf8_bin" for encoding "UTF8" does not exist at character 128 (SQL: create table "taggable_tags" ("tag_id" bigserial primary key not null, "name" varchar(255) not null, "normalized" varchar(255) collate "utf8_bin" not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null))

```

### Steps To Reproduce:

1.  Fresh installation of laravel
2.  Change  `.env`  to use postgres as driver
3.  Add cviebrock/eloquent-taggable as dependency
4.  `php artisan migrate`

**Comment by 0528Makoto** [comment]
add a small change for the tests to pass, but it would be necessary to test in other drivers (sqlserver, sqlite)

**Comment by cviebrock** [comment]
Merged and bumped the version.  I'll have to spend a bit more time to make sure this works with the other drivers.  Thanks!!
