### ISSUE TITLE
Incompatible w/ MariaDB 10.5.8

### ISSUE THREAD

**Issue by HomeMatic-INSIDE** [cviebrock/eloquent-taggable#125]
Good morning,

my hoster has changed the database from MySQL to MariaDB (10.5.8) and now, all requests w/ tags are throwing the following error:

`production.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1055 'd02937f7.articles.user_id' isn't in GROUP BY (SQL: select `articles`.* from `articles` inner join `taggable_taggables` on `articles`.`id` = `taggable_taggables`.`taggable_id` and `taggable_taggables`.`taggable_type` = App\Article where `taggable_taggables`.`tag_id` in (61) ...`

This seems to happen due of a missing "group-by". I'm still using version 3.3 - so don't know, if this happens in further versions, too.

Regards,...

**Comment by cviebrock** [comment]
This might be an issue with strict mode.  See issue #60 for some of the history on this.

Version 3.3 is a bit old now, so you might want to try updating that first.
