### ISSUE TITLE
Model with popularTags not apply global scope

### ISSUE THREAD

**Issue by Kotzilla** [cviebrock/eloquent-taggable#126]
I use a model with taggable. 
Content::popularTags() but Content have a global scope with where('status', 'published');

it's return without filter condition
is it the way to filter the popularTags ? 
i'have try with  Content::where('status', 'published')->popularTags(20);

Thank you.

**Comment by Kotzilla** [comment]
@cviebrock 

yes i try but it's return 

`call to undefined method Illuminate\Database\Eloquent\Builder`

**Comment by cviebrock** [comment]
Closing old issue
