### ISSUE TITLE
Get Model by tag_id

### ISSUE THREAD

**Issue by rationalthinker1** [cviebrock/eloquent-taggable#127]
I have a `tag_id` of a tag that I want to delete. I need the `$model` for me to detag it. Something like this below.

```php
$tag = Tag::find("tag_id");
$model = $tag->taggable;
$model->tags()->detach( $tag );
```

**Comment by cviebrock** [comment]
You would need to set the [taggedModels](https://github.com/cviebrock/eloquent-taggable#taggedmodels) configuration.

That said, it would probably be nice to add a `$tagService->deleteTag(...)` method that removed the tag and also detagged all the attached models.  I'll figure something out shortly.
