### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by tcs-mpcs** [cviebrock/eloquent-taggable#138]
Thank you for developing this package.

I tried updating to Laravel 10 and got the following error from composer.

Do you have any update plans for Laravel 10?

Thank you.

```json
"require": {
    "cviebrock/eloquent-taggable": "^9.0",
}
```

```
Problem 1
    - cviebrock/eloquent-taggable 9.0.0 requires illuminate/config ^9.0 -> found illuminate/config[v9.0.0, ..., v9.52.0] but these were not loaded, likely because it conflicts with another require.
```

**Comment by cviebrock** [comment]
I'm working on it now, but I think something has changed with the way inverse relations are handled in Eloquent.  Just investigating now, but feel free to pull the `laravel-10` branch and check it out.

**Comment by cviebrock** [comment]
New version pushed!
