### ISSUE TITLE
What is the best way to truncate for a Model

### ISSUE THREAD

**Issue by lorvent** [cviebrock/eloquent-taggable#147]
Please be sure you include all the relevant information in your issue so we can help you:

lets imagine i have a section `blog` and whenever i want to seed dummy data into it, i would truncate all existing data like  truncate `blog, `blog_categories`, `blog_comments` tables etc

now how to truncate all tags associated with all blogs in `blog` table?

do i need to loop through all of them or is there any easy method?

thanks.

**Comment by cviebrock** [comment]
If you're truncating everything, can you not just truncate the `taggable_tags` and `taggable_taggables` tables as well?

**Comment by lorvent** [comment]
no, i don't think thats better.

lets say i am using tags feature for both `news` and `blog` model and i am truncating `blog` so i only want to delete all related tags for `blog` model

right now i am doing `DB::table('taggable_taggables')->where('taggable_type', 'App\Models\Blog')->delete();`
but wondering if there is any better method?

**Comment by cviebrock** [comment]
Ah, I see what you mean.  I think this should work then:
```php
// Instantiate the service (can also be done via dependency injection)
$tagService = app(\Cviebrock\EloquentTaggable\Services\TagService::class);

// Find all the tags that aren't used by any model and delete them
$tagService->getAllUnusedTags()->delete();
```

**Comment by lorvent** [comment]
Thank you!

you are answering `taggable_tags` which is good for me because my method doesn't delete from that table

but my original question is, how to delete/truncate (when doing db:seed again and again) in `taggable_taggables` table for a particular model say Blog `App\Models\Blog`

thanks.

**Comment by cviebrock** [comment]
Without looping through them in code, I don't think this is possible.  The best option would probably require updating the schema for the `taggable_taggables` table to reference the `taggable_tags` FK do a cascade on delete.

PR #104 did have something like this, but it ended up not getting merged due to backwards compatibility issues.  But offhand, I don't see an issue with that part of the migration.  i.e. something like (untested):
```
$table->foreign('tag_id')
      ->references('tag_id')
      ->on('taggable_tags')
      ->onDelete('cascade');
```

**Comment by lorvent** [comment]
ok.... i guess easiest is to merge these two

1. truncate a Models existing records with 
 
```php 
DB::table('taggable_taggables')->where('taggable_type', 'App\Models\Blog')->delete();`
```
then
2. remove all tags unused anywhere with
```php
// Instantiate the service (can also be done via dependency injection)
$tagService = app(\Cviebrock\EloquentTaggable\Services\TagService::class);

// Find all the tags that aren't used by any model and delete them
$tagService->getAllUnusedTags()->delete();
```

cascading in my opinion is load on server, because i feel a direct cascade doesn't work for us
Ex: a tag called "technology" may be used on multiple models like blogs, thesis, news in a single project.

**Comment by cviebrock** [comment]
What I was suggesting (and probably my sql/migration is incorrect because I don't have it in front of me to play with) is that when a model is deleted, the linking entry from the `taggable_taggables` table is also deleted.  Not the tag itself.

**Comment by lorvent** [comment]
ok, Gotcha!

Thanks for your time :)
