### ISSUE TITLE
Dependencies broken?

### ISSUE THREAD

**Issue by nickcoad** [cviebrock/eloquent-taggable#16]
There seems to be something wrong with the dependencies.  When I try to use this with the latest version of Laravel, the following occurs:

    $ composer require cviebrock/eloquent-taggable
    Using version ^1.0 for cviebrock/eloquent-taggable
    ./composer.json has been updated
    > php artisan clear-compiled
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.
    
      Problem 1
        - Installation request for cviebrock/eloquent-taggable ^1.0 -> satisfiable by cviebrock/eloquent-taggable[1.0.0].
        - Conclusion: remove laravel/framework v5.1.9
        - Conclusion: don't install laravel/framework v5.1.9
        - cviebrock/eloquent-taggable 1.0.0 requires illuminate/support 4.* -> satisfiable by
            illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7,
            v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15,
            v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24,
            v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6,
            v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5,
            v4.2.6, v4.2.7, v4.2.8, v4.2.9].
        - don't install illuminate/support v4.0.0|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.0.1|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.0.10|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.0.2|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.0.3|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.0.4|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.0.5|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.0.6|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.0.7|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.0.8|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.0.9|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.0|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.1|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.10|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.11|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.12|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.13|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.14|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.15|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.16|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.17|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.18|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.19|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.2|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.20|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.21|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.22|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.23|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.24|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.25|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.26|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.27|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.28|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.29|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.3|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.30|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.4|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.5|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.6|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.7|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.8|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.1.9|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.1|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.12|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.16|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.17|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.2|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.3|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.4|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.5|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.6|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.7|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.8|don't install laravel/framework v5.1.9
        - don't install illuminate/support v4.2.9|don't install laravel/framework v5.1.9
        - Installation request for laravel/framework == 5.1.9.0 -> satisfiable by laravel/framework[v5.1.9].

    Installation failed, reverting ./composer.json to its original content.

**Comment by cviebrock** [comment]
You want either `dev-master` or the `2.0.0-beta` version for Laravel 5.

**Comment by cviebrock** [comment]
Also, did we just meet at Laracon talking to Ed Finkler? :)

**Comment by nickcoad** [comment]
@cviebrock no, but I wish!  I'm in Australia so getting to either of the Laracon's is difficult :(
