### ISSUE TITLE
How to get tag that has post(s)

### ISSUE THREAD

**Issue by dinajpuri** [cviebrock/eloquent-taggable#20]
Hello,
Could you pls give me some hint how to get **tags those have posts** and a **tag with all posts attached** to it (as in Wordpress)?

Regards

**Comment by cviebrock** [comment]
Currently this isn't possible, but should be something I could add in the next 2.x version.

**Comment by cviebrock** [comment]
This is part of the upcoming 3.x release.  Feel free to checkout `dev-master` and let me know how it works for you.
