### ISSUE TITLE
not compatible with 5.2

### ISSUE THREAD

**Issue by lorvent** [cviebrock/eloquent-taggable#24]
Hi,

I guess it has same issue like https://github.com/cviebrock/eloquent-sluggable/issues/214

looks like laravel-5-refactor branch seems to be solving it :smile:

**Comment by cviebrock** [comment]
Yeah, just working on that. ;)  Give me a few days to get the test suite working, and I'll make a new release.

**Comment by lorvent** [comment]
Thank you so much for your efforts and quick reply :+1:
