### ISSUE TITLE
Composer Namespace has been changed and breaks the Package with L5.2

### ISSUE THREAD

**Issue by superdummy** [cviebrock/eloquent-taggable#25]
Just as a note: 

`Illuminate\Foundation\Composer` has been changed to  `Illuminate\Support\Composer` in L5.2

It is used in https://github.com/cviebrock/eloquent-taggable/blob/master/src/Console/TaggableTableCommand.php#L6
and it would be great if it would be updated. 

Further Reference (they discuss the problem in detail and also mention taggable as an Package that breaks with this change).
http://stackoverflow.com/questions/34465721/laravel-5-1-to-5-2-upgrade-error

**Comment by cviebrock** [comment]
I'm in the process of fixing this package (ran into some other issues).  You can try the `dev-laravel-5-refactor` branch in the meantime, until I get a proper release out.

**Comment by superdummy** [comment]
Thanks a million times! Your packages are so great and helpfull!

**Comment by cviebrock** [comment]
Try the `2.0` branch which fixes lots of Laravel 5.1+ issues.  In short, the package doesn't try and run the migration for you; it just generates it.
