### ISSUE TITLE
Laravel artisan config:cache is broken by normalize Closure

### ISSUE THREAD

**Issue by superdummy** [cviebrock/eloquent-taggable#26]
Hi, 

I could have sworn I saw this already coumented somewhere (maybe it was with one of your other libraries) but there is no open Issue here on taggable. 

The following code in the `config/taggable.php` config file breaks the laravel `config:cache`, as no Closures are supported. 

`//Custom Slugger`
`'normalizer' => function($string) {`
` 	$slugify = new \Cocur\Slugify\Slugify();`
`	return $slugify->slugify($string);`
`}`

Thanks!

**Comment by cviebrock** [comment]
Sorry for the delayed response.  If you install the facade for Slugify as described [here](https://github.com/cocur/slugify#laravel), perhaps this would work:

```php
'normalizer' => [ 'Slugify', 'slugify' ]
```
