### ISSUE TITLE
Feature request: support to get all tags by taggable_type/Model, as list and array

### ISSUE THREAD

**Issue by jonascarlbaum** [cviebrock/eloquent-taggable#3]
Great work on ```eloquent-taggable```. ;)

I did work in RoR before and was loving ```acts-as-taggable-on``` at that time.

One thing I miss in this implementation, which I would really appreciate, is the possibility to do something like:
```Model::tagList``` or ```Model::tagArray``` to get a list of all possible tags for that model, not only for the instance.

Having this functionality it would be easy to render tags for the model and use with something like [textext autocomplete with tags](http://textextjs.com/manual/examples/autocomplete-with-tags.html).

Guess I can do some queries to achieve it anyway (and that's what I'll do right now), but would love if this feature was built-in here... ;)

**Comment by cviebrock** [comment]
This will be part of the Laravel 5 release that I'm currently working on.  Thanks for the suggestion!

**Comment by Shonetow** [comment]
Hi, I'm getting empty results.

Is this line ok?
`->join('taggable_tags', 'taggable_taggables.taggable_id', '=', 'taggable_tags.tag_id')`

because `taggable_id` is a model id and `tag_id` is... well... tag id?
