### ISSUE TITLE
Multiple tag types

### ISSUE THREAD

**Issue by lorvent** [cviebrock/eloquent-taggable#30]
Hi,

I have Portfolio model where i want to use eloquent-taggable for 2 field types
1. technologies
2. tags

but the problem is since we have to do $portfolio->add(); its not able to distinguish whether a tag related to technologies or tags.

can you show me a better way to achieve this?

Thanks.

**Comment by cviebrock** [comment]
Hrmm ... I don't think something like this is possible right now. Let me think about how best to do it, and I'll add it to the next version.

Thanks!

**Comment by lorvent** [comment]
Hmm, thanks for the response.

so far we did like this

Portfolio has 2 tag sections `technologies and tags`

so created 2 intermediate models Technology.php, Tag.php and tables and storing relation info.

its not a good approach but the only possible hack for timebeing.

**Comment by skattabrain** [comment]
+1 - I could use this as well... I have a situation where my asset will have several types of tags. For example... color, medium, subject.

In a previous app before the Laravel days, I approached it by making tags like this... "Color / Red", "Color / Blue",  "Subject / Abstract" and "Subject / Fine Art".

I would then explode them out using the / and I could essentially have my input control like this...

Label - Color
Tag List - Red, Blue

Label - Subject
Tag list - Abstract, Fine Art

It allowed me to have 1 table and then in my UI I would explode the tag by / and display the last item in the array.

**Comment by elephantux** [comment]
+1

**Comment by Cigoler** [comment]
I notice there is a taggable_type in the taggable_taggables table. Is it possible to differentiate between models therefore? So you could have a product model, and an articles model and limit searches between t hem that way?

**Comment by avasiliev87** [comment]
It would be great if it provide tag context.
$video->tag(['love'], 'feature');

VideoModel::tagsWithContext('feature');
VideoModel::tagsWithContext('action');
VideoModel::tagsWithContext('animation');

**Comment by cviebrock** [comment]
I like that approach, @avasiliev87 .  I'll definitely add this to the next major version.  Or feel free to submit a PR!
