### ISSUE TITLE
[ Question ] What if I update model namespace

### ISSUE THREAD

**Issue by abhimanyusharma003** [cviebrock/eloquent-taggable#31]
Currently all my models in in `app` folder with namespace `App`

But how can I update the database, lets say if I update the model namespace to something like `App\Foo\Models` 

Thanks

**Comment by cviebrock** [comment]
You would probably just need to run a migration or DB query to update the taggable table, renaming the class names there.

Hopefully this is a one-time change, and not a recurring thing.
