### ISSUE TITLE
There are no commands defined in the 'taggable' namespace

### ISSUE THREAD

**Issue by ruddell-mbible** [cviebrock/eloquent-taggable#33]
Running Laravel 5.2 and getting an error when running this command:

php artisan taggable:table

error:
 [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "taggable" namespace. 

---------
My composer.json file:
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "cviebrock/eloquent-taggable": "^2.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*",
        "laravelcollective/html": "5.2.",
        "cartalyst/sentinel": "2.0.",
        "cviebrock/eloquent-sluggable": "^3.1.4",
        "yajra/laravel-datatables-oracle": "~5.0"
    },

**Comment by cviebrock** [comment]
Did you load the ServiceProvider?

**Comment by osnwach** [comment]
I am having exactly the same issue ! 

I am using Laravel 5.1

Please how can I resolve this issue ?


This command:  php artisan taggable:table

Gives Error:

 [InvalidArgumentException]
  There are no commands defined in the "taggable" namespace.

**Comment by cviebrock** [comment]
Actually, where are you seeing the instructions to run `php artisan taggable:table`?

If you follow the [installation steps](https://github.com/cviebrock/eloquent-taggable#installation), that command is no longer required as of version 2.0 of the package.  Publishing the package should publish the configuration and create a migration for you.

**Comment by neverover** [comment]
I am having exactly the same issue too 
I am using Laravel 5.1 
when i try to add blog category i get this 
error: Interface 'Cviebrock\EloquentTaggable\Contracts\Taggable' not found

also i can't run the taggable table command in terminal ?

any help please

**Comment by cviebrock** [comment]
You are all installing the `3.x` version of the package, but the README on the homepage is for the `4.x` version.  Please follow the correct installation steps as mentioned in my last comment.

**Comment by cviebrock** [comment]
Please read the installation instructions and use the most recent version of the package.  Y'all are running commands and looking for classes that no longer exist in the package.

**Comment by neverover** [comment]
thanks for answering my question.
please i may seem lost but  know this i'm in the final step of the installation, everything works correctly but when i try to add a new 
error: Interface 'Cviebrock\EloquentTaggable\Contracts\Taggable' not found ---Blog.php : line12

can't publish or generate  the taggable service provider and migration file.
    i'am using      "cviebrock/eloquent-taggable": "^2.0.0-beta",   --- Laravel 5.1

help me because i can't find anything in the documentation to resolve the problem
