### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by gkjpettet** [cviebrock/eloquent-taggable#34]
I get the above warning from composer when I install your package. How would I switch to the recommended package?

Thanks for a great package btw.

**Comment by cviebrock** [comment]
Thanks!

The warning comes from the `scrutinizer/ocular` package, which was listed as a requirement, but is only needed for development (running the package tests, etc.).  The haven't updated their package it seems, but I've fixed the `composer.json` file in the master branch for my package so you shouldn't see that warning (if you install with `--no-dev`).  I'm not going to push a new release, though, just for that change, so you'll have to wait until the next version unless you use `dev-master`.

In any case, you can safely ignore that warning.

**Comment by cviebrock** [comment]
You may also see:

> Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.

Safe to ignore that as well (and I'll fix it in the next release).
