### ISSUE TITLE
Trait 'Cviebrock\EloquentTaggable\Taggable' not found

### ISSUE THREAD

**Issue by stuchin** [cviebrock/eloquent-taggable#35]
i use Laravel 5.2

in my composer.json
   "cviebrock/eloquent-taggable": "dev-laravel-5-refactor",

where can be error?

**Comment by cviebrock** [comment]
Just use the latest stable branch, which is fine with 5.2

**Comment by stuchin** [comment]
"cviebrock/eloquent-taggable": "dev-master",  ?

**Comment by stuchin** [comment]
ok

**Comment by stuchin** [comment]
huge thanks everything works
great job

**Comment by cviebrock** [comment]
I'd recommend `^2.0` over `dev-master`.
