### ISSUE TITLE
Tag suggestions

### ISSUE THREAD

**Issue by lukasoppermann** [cviebrock/eloquent-taggable#36]
Hey, something very interesting would be to do some basic tag suggestion.

I think 2 ways would be possible:
1. `->mostUsed(10)` could just give you the 10 most used tags
2. `->suggestRelated('php')` could give you related tags to the tag `php`

Related tags could be retrieved by getting all items with this tag and getting all tags that those items have. Afterwards they could be counted and all tags with a count above a certain threshold would be returned.

**Comment by cviebrock** [comment]
Excellent ideas! I'm happy to accept PRs if you want to code these yourself. Or I'll add them in the next version.

**Comment by lukasoppermann** [comment]
Hey @cviebrock I don't think I will be able to add this any time soon, as I did not work myself into the package yet and have no idea how to implemented it with the package. So if you could add it in the next version, I would really appreciate it. 👍

**Comment by cviebrock** [comment]
Going through old issues and I think this can be done with current methods.  Sample code below has been minimally tested, and I'm sure could be improved, but ...

> `->mostUsed(10)` could just give you the 10 most used tags

```php
$mostUsed = array_keys(TestModel::popularTags(10));
```

> `->suggestRelated('php')` could give you related tags to the tag php
> Related tags could be retrieved by getting all items with this tag and getting all tags that those items have. Afterwards they could be counted and all tags with a count above a certain threshold would be returned.

```php
$models = TestModel::withAllTags('Banana')->get();

$allTags = $models->map(function($model) {
    return $model->tagArray;
});

$relatedTop5 = collect($allTags)
    ->collapse()
    ->countBy()
    ->except('Banana')
    ->sortDesc()
    ->take(5);
```
