### ISSUE TITLE
queries are very slow

### ISSUE THREAD

**Issue by belst** [cviebrock/eloquent-taggable#37]
I noticed that stuff like `withAllTags()` and so on is using dependend subqueries (the select count part)

this makes querying larger datasets very slow.

Some example data:

``` php
<?php
use \App\Models\Video;

$start = time(); // no need for microtime. it takes forever anyway
$c = Video::withAllTags('sfw')->count();
echo 'Time passed: ', time() - $start, ' seconds', PHP_EOL;
echo 'Records with tag \'sfw\': ', $c, PHP_EOL;
```

output: 

```
Time passed: 140 seconds
Records with tag 'sfw': 11019
```

I cant wait 140 seconds for such an easy query.

---

number of Videos in db: 12258
number of Tags in db: 9135
number of Relations video <-> tag: 40421

Not only does it take forever. it has a HUGE impact on the CPU.

**Comment by cviebrock** [comment]
Thanks.  I'll look at this eventually, but if you have a PR with a more optimized query, I'd be happy to merge it.
