### ISSUE TITLE
Tag Groups

### ISSUE THREAD

**Issue by StanBarrows** [cviebrock/eloquent-taggable#38]
First of all, thank you for this package! Great work and i consider to invest some little more time to implement it in my application. 

If you thinking about an further development, i would like to throw in **Tag-Groups.**

- Add Tags to a Tag Group
- Ability to add one Tag do different groups
- Methods for groups

Cheers, 
Seabstian

**Comment by a-komarev** [comment]
@SebastianFix Will be great to see tag groups in this package.

**Comment by yasu** [comment]
👍

**Comment by cviebrock** [comment]
It's on the to-do list!

**Comment by cviebrock** [comment]
Just looking into implementing some of these enhancements now.  Wouldn't tag groups work simply by creating a Group model and making it taggable as well?

**Comment by a-komarev** [comment]
Will it fit this requirement:
Tag Group: `sport`
Tags: `football`, `hockey`

And when We are searching in `sports` group it should show `football` and `hockey` tags contents.

**Comment by cviebrock** [comment]
I feel I need a bit of a better idea of how this feature would be used.  Right now, you could just create your own TagGroup model:

```php
class TagGroup extends Model {
    use Taggable;
}
```

Then, create and tag the groups accordingly:

```php
$group = new TagGroup(['name'=>'sports']);
$group->tag('football,hockey');
```

Then, say you have an Event model which you are tagging with 'Football', 'Hockey', etc., and you want to find all Events that are sports.

```php
$group = TagGroup::where('name','sports')->first();
$sportTags = $group->tagArray();

$events = Event::withAnyTags($sportTags)->get();
```

This should work in the 3.x version which is in beta right now.  Feel free to checkout the `dev-master` branch and let me know.

**Comment by a-komarev** [comment]
Thanks. I'm gonna start checking it in early of July.
