### ISSUE TITLE
Eloquent-taggable not installing  on laravel 5.2 

### ISSUE THREAD

**Issue by zohaib055** [cviebrock/eloquent-taggable#45]
i have been using laravel 5.2 and i have composer.json file having the following dependency

"cviebrock/eloquent-taggable": "dev-master", but it throughs an error i manually put the package in vendor

but  it throughs an error   Class 'Cviebrock\EloquentTaggable\ServiceProvider' not found   let me know the how to fix this issue i will thankful

**Comment by cviebrock** [comment]
You need to pin the version to 2.0 if you are using Laravel 5.2.  `dev-master` would be for Laravel 5.4+

```json
"cviebrock/eloquent-taggable": "2.0.*"
```

**Comment by zohaib055** [comment]
ok thanks got it working
