### ISSUE TITLE
Get Models without specific tag?

### ISSUE THREAD

**Issue by marcreichel** [cviebrock/eloquent-taggable#48]
Hi there,

is it possible to get all models that do not have a specific tag?
Something like:
`Model::withoutAllTags('banana,apple,pineapple')`
and/or
`Model::withoutAnyTags('banana,apple,pineapple')`

Thanks in advance

**Comment by cviebrock** [comment]
Not yet, but I'm working on it. :)

**Comment by cviebrock** [comment]
This is in the code now, coming to version 3.0 in the next few days.  Feel free to test it using the `dev-master` tag and let me know how it works.
