### ISSUE TITLE
I think that there is a better solution!

### ISSUE THREAD

**Issue by nilsenj** [cviebrock/eloquent-taggable#6]
I have seen that if we have some repetitions in tags their names reference to the previous tags Ids!
maybe it is better to create a third database which will have the filtered and unique names!
And taggable_tags will just refference the unique names by id !!!
by the way it is really good package and what i was really searching! but with some bugs i would say(

**Comment by cviebrock** [comment]
Interesting idea.  I haven't actually used this package much lately, but that seems like a good solution.  Maybe for the next version!
