### ISSUE TITLE
Retuurn collection with tags

### ISSUE THREAD

**Issue by readergirltracey** [cviebrock/eloquent-taggable#62]
How do i get all tags when returning a collection?

`
Article::with('tags')->published()
            ->latest()
            ->paginate(7);
`
This does not work

**Comment by cviebrock** [comment]
You figured it out?  The above _should_ work, depending on how your `published` and `latest` query scopes are written.

But, you could always do:

```
$articles = Article::published()->latest()->paginate(7);
$articles->load('tags');
...
```

**Comment by readergirltracey** [comment]
yes i did
