### ISSUE TITLE
FindByName

### ISSUE THREAD

**Issue by readergirltracey** [cviebrock/eloquent-taggable#63]
`$articles = Tag::findByName($tag)->articles;
`
Calling that throws the following error

**Call to undefined method Illuminate\Database\Query\Builder::findByName()**

I added article class to taggedModels
`'taggedModels' => [
        'articles' => \App\Entities\Article::class
    ]
`

**Comment by cviebrock** [comment]
Which version of Laravel and which version of this package are you using?

**Comment by readergirltracey** [comment]
laravel 5.4, php 5.6, version 2.*

**Comment by cviebrock** [comment]
`findByName` and the `taggedModels` configuration were added in 3.*.

You'll need to update to at least version 3.0 of the package, preferably 3.1, although both of those will require PHP7 as well.
