### ISSUE TITLE
Paginate Popular Tags

### ISSUE THREAD

**Issue by keithgulbro** [cviebrock/eloquent-taggable#67]
Hi there,

Thanks for creating a great package! I ran into a situation in which I'd like to paginate the popularTags returned by a given model however when I attempt to execute something like the following: 

`Model::popularTags->paginate(10);` 

since the data returned is in array instead of a collection form the standard `->paginate()` method doesn't work. 

Could you please advise?

**Comment by cviebrock** [comment]
`collect(Model::popularTags)->paginate(10);` maybe?

**Comment by keithgulbro** [comment]
Thank for responding, your answer was helpful!
