### ISSUE TITLE
Update To Laravel 5.6

### ISSUE THREAD

**Issue by stevepop** [cviebrock/eloquent-taggable#71]
Please be sure you include all the relevant information in your issue so we can help you:

- [ Ran composer update to push Laravel to 5.6] 
- [ composer.json ] your configuration file(s), where relevant

Output from composer;

```
 Problem 1
    - cviebrock/eloquent-taggable 3.2.5 requires illuminate/support ~5.5.0 -> satisfiable by laravel/framework[v5.5.33], illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34]
```
Thank you.

**Comment by cviebrock** [comment]
Laravel 5.6 isn't even out yet. ;)

But when it is, I'll tag a new version here (likely 3.3) that you can use.

**Comment by stevepop** [comment]
@cviebrock Laravel 5.6 was released yesterday :)

**Comment by cviebrock** [comment]
Version 3.3.* of the package has now been released.
