### ISSUE TITLE
3.1 custom model

### ISSUE THREAD

**Issue by nicgutierrez** [cviebrock/eloquent-taggable#73]
Hi, this is more of a question.

Is there any way in v 3.1 to use a custom model?

Thanks,
Nic

**Comment by nicgutierrez** [comment]
nvm, I just realised I can override the tags method and return the model I want :)

Cheers

**Comment by cviebrock** [comment]
Yeah, I only added this feature to the latest version. If you wanted to make a PR to back port this feature, I’d happily accept it!
