### ISSUE TITLE
Scopes return SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by csb346** [cviebrock/eloquent-taggable#74]
Hi! I need some help.

I already used this package on other projects without any problem. This time I don't understand why, but scopes are returning an sql syntax error. A simple example test:

```
$article->tag('banana');
$tagged = Article::withAllTags('banana')->get();

SQLSTATE[42000]: Syntax error or access violation: 1055 'wr.articles.title' isn't in GROUP BY (SQL: select `articles`.* from `articles` inner join `taggable_taggables` on `articles`.`id` = `taggable_taggables`.`taggable_id` and `taggable_taggables`.`taggable_type` = App\Article where `taggable_taggables`.`tag_id` in (695) group by `articles`.`id` having COUNT(taggable_taggables.tag_id) = 1)
```

Any idea why? I can't find any error. Anyway this query is from the package and never had any problem before.

Thanks.

**Comment by cviebrock** [comment]
I'm going to guess it's related to https://github.com/cviebrock/eloquent-taggable/issues/60#issuecomment-330493812 ... which really doesn't have a fix, since I can't know what all the columns are in your `articles` table.

Unless you can turn off strict mode, I don't have an easy solution.

**Comment by avasiliev87** [comment]
I got this error too

**Comment by cviebrock** [comment]
I'm definitely open to a PR that can fix this.

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.

**Comment by MordiSacks** [comment]
This is my solution
```php
$tags = ['tag1', 'tag2', 'tag3'];

$taggable = Taggable::query();

foreach ($tags as $tag) {
    $taggable->whereHas('tags', function (Builder $q) use ($tag) {
        $q->where('normalized', $tag);
    });
}
```

got it from here
https://github.com/spatie/laravel-tags/blob/master/src/HasTags.php#L79

**Comment by Thehornyboy** [comment]
hey thanks for the efforts was put to build up this package,
unfortuantely I am also encountering this issue.thanks
