### ISSUE TITLE
Model::isTagged()->get() doesn't return any items in Laravel 5.4

### ISSUE THREAD

**Issue by yurivis** [cviebrock/eloquent-taggable#75]
I'm using this package to save tags associated with certain uses. Saving tags works without any issues. I have checked my database and confirmed that the tags are connected with the appropriate users. When I try to call User::isTagged()->get() it returns an empty collection. Using User::isNotTagged()->get() returns all users, even the ones that are tagged.

**Comment by cviebrock** [comment]
Sorry for the delayed reply.

Any chance you can log the DB queries being generated in both those cases and post them here?  Adding something like `DB::connection()->enableQueryLog();` before those calls, then `dd(DB::getQueryLog());` afterwards should do it.
