### ISSUE TITLE
Publish configuration laravel 5.6

### ISSUE THREAD

**Issue by loic-lopez** [cviebrock/eloquent-taggable#76]
Hello,

I use **laravel 5.6** and your package version **3.3.1**, and i ran to an issue with the publish command take a look bellow: 

<img width="776" alt="capture d ecran 2018-05-09 a 15 53 34" src="https://user-images.githubusercontent.com/17724398/39818425-2b67cb86-53a1-11e8-8b47-d56cd543ccd0.png">

It does not publish the migration.

Thanks for reply 👍

**Comment by cviebrock** [comment]
I'm unable to reproduce this issue:

```sh
> laravel new l56
...

> cd l56
> composer require cviebrock/eloquent-taggable
Using version ^3.3 for cviebrock/eloquent-taggable
...

> php artisan migrate
Migration table created successfully.
Migrating: 0000_00_00_000000_create_taggable_table
Migrated:  0000_00_00_000000_create_taggable_table
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
```

Perhaps the confusion is from what I wrote in the documentation:

> 2. Publish the configuration file and migrations:

In reality, only the configuration is published.  The migrations are run out of the package directly (without needing to be published to `/database/migrations`).  I'll update the docs.
