### ISSUE TITLE
Detag on delete

### ISSUE THREAD

**Issue by pierrocknroll** [cviebrock/eloquent-taggable#77]
Hello,

It could be great for the database consistency to detag on a deleted model (if it is not soft deleted).

I think you can do something like : 
```php
static::deleting(function ($model) {
    if (!method_exists($model, 'runSoftDelete') || $model->isForceDeleting()) {
        $model->detag();
    }
});
```

Thanks

**Comment by cviebrock** [comment]
The main idea being that it would help clean up the polymorphic table, right?

**Comment by pierrocknroll** [comment]
Yeah, ok I'll do it !
