### ISSUE TITLE
Tag user/owner

### ISSUE THREAD

**Issue by scottybo** [cviebrock/eloquent-taggable#82]
Let's say we have a model "Widgets" and our system has 3 users. User A creates a Widget and tags it with "yellow,blue". User B creates a Widget and tags it with "yellow,pink". User C didn't set any tags for their Widget.

I now want to show User A and B the tags they've created or used.

So in the system I'll show User A "yellow,blue" and User B "yellow,pink". and User C will be told they haven't created any tags yet.

**Comment by cviebrock** [comment]
The package doesn't support something like this, out-of-the-box unfortunately.  I'm definitely open to a PR to add this though ... it sounds like it could be useful.

One option would be to create/use an intermediate model -- `UserWidget` -- and tag that.
