### ISSUE TITLE
Tagging other models

### ISSUE THREAD

**Issue by asivaneswaran** [cviebrock/eloquent-taggable#83]
Hi,

I want to know if it's possible to tag other models.
Let's say I have there are multiple teams (models) and I write an article (model) for them. I would like to tag those teams to the article. I thought about adding the name as a tag but as there can be multiple seasons, so multiple teams with the same name, that woudn't work.

Any ideas?

Thanks,

**Comment by cviebrock** [comment]
I'm not 100% clear on what you are asking, but it sounds like a simple polymorphic relationship between `Team` and `Article` models would work, no?

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
