### ISSUE TITLE
Sync tags without removing and adding them

### ISSUE THREAD

**Issue by LeonAlvarez** [cviebrock/eloquent-taggable#92]
Hi, is there a way to sync tags, retag is removing all tags and them adding them back. Im auditing the tags add / remove so this causes more more actions than it should.

**Comment by cviebrock** [comment]
From a SQL point of view, you're going to have to remove the relations and then insert them anyway.  So I'm not sure how this would work with "fewer actions".

I'm open to suggestions, though.

**Comment by bogordesaincom** [comment]
same problem

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.

**Comment by suth** [comment]
I think the desired behavior
