### ISSUE TITLE
Not Saving Tags to taggable_taggables Table

### ISSUE THREAD

**Issue by reasecret** [cviebrock/eloquent-taggable#93]
I'm trying to use this package.

When I'm adding new tags, records are saving to taggable_tags table but not saving to taggable_taggables table. So I can't get tagList. There is no error. What shoult I do to fix this?

I'm using laravel 5.8.4 and cviebrock/eloquent-taggable 3.5.

**Comment by cviebrock** [comment]
I'm not sure.  Can you post some code that shows this behaviour (including any configuration files)?

**Comment by reasecret** [comment]
Ok my mistake. I've belongsToMany relationship on my model named **tags**. I just removed this relationship and now records are saving. Thank you for your interest.
