### ISSUE TITLE
Display all tags with count

### ISSUE THREAD

**Issue by timgavin** [cviebrock/eloquent-taggable#96]
Is there a way to display all tags (not popular tags, but ALL tags) with a count of how many times they have been used?

**Comment by cviebrock** [comment]
Tags are just regular Eloquent models, so you can query them directly.  See https://laravel.com/docs/5.8/eloquent-relationships#counting-related-models 

Something like this would probably work (untested):

```php
$tags = Tag::withCount('taggedModels')->get();
```

**Comment by tfevan** [comment]
In your controller
`public function taglist(Request $request)
    {
        $tags = Post::allTagsList();
        return view('front.taglist', ['tags'=> $tags]);
    }`

In your views
`@foreach ($tags as $name => $count)
						   
	<a href="../hashtag/{{ $name }}">
	<li class="tag">
	{{ $name }} <span class="badge badge-dark">{{ $count }}</span>
	</li>
	</a>
@endforeach	  `

Hope this helps :)

**Comment by d1moncom** [comment]
`$tags = Tag::withCount('taggedModels')->get();`
> Call to undefined method Cviebrock\EloquentTaggable\Models\Tag::taggedModels()

$tags = Post::allTagsList();
dd($tags);
> "tag1,tag2,...,tag100500"

Both methods do not give results.

**Comment by cviebrock** [comment]
You are right: neither of those options work.

However, `getPopularTags` just does a count on the tags, so this should give you what you want:

```php
        $tags = app(TagService::class)
            ->getPopularTags(null, null, 0)
            ->pluck('taggable_count', 'normalized')
            ->toArray();
```
