### ISSUE TITLE
Add colour to tags

### ISSUE THREAD

**Issue by philippejadin** [cviebrock/eloquent-taggable#98]
I'm currently using this package with great success. I'd like to ass colour to tags. Am I correct that I just need to add a migration to add the appropriate columns then I'll be able to access those colours from the related tag model ? Anything I should watch for?

Thanks!

**Comment by cviebrock** [comment]
That sounds to me like all you'll need to do.  You can also change the Tag model itself to something custom (that extends the package's Tag model) using the `model` setting in the config.  That might make things easier for you (so any colour logic can go in your extended class).
